// Flinch probabilities for all moves capable of flinching, sourced from Bulbapedia.
pub const FLINCH_MOVES: &[(&str, u64)] = &[
    ("Air Slash", 30),
    ("Astonish", 30),
    ("Bite", 30),
    ("Bone Club", 10),
    ("Dark Pulse", 20),
    ("Double Iron Bash", 30),
    ("Dragon Rush", 20),
    ("Extrasensory", 10),
    ("Fake Out", 100),
    ("Fiery Wrath", 20),
    ("Fire Fang", 10),
    ("Fling", 100),
    ("Floaty Fall", 30),
    ("Headbutt", 30),
    ("Heart Stamp", 30),
    ("Hyper Fang", 10),
    ("Ice Fang", 10),
    ("Icicle Crash", 30),
    ("Iron Head", 30),
    ("Low Kick", 30),
    ("Mountain Gale", 30),
    ("Needle Arm", 30),
    ("Rock Slide", 30),
    ("Rolling Kick", 30),
    ("Secret Power", 30),
    ("Sky Attack", 30),
    ("Snore", 30),
    ("Steamroller", 30),
    ("Stomp", 30),
    ("Thunder Fang", 10),
    ("Triple Arrows", 30),
    ("Twister", 20),
    ("Upper Hand", 100),
    ("Waterfall", 20),
    ("Zen Headbutt", 20),
    ("Zing Zap", 30),
];
